CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    city VARCHAR(255),
    website VARCHAR(255),

    CONSTRAINT company_pkey
        PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phonenumber VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT users_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_users_email
        UNIQUE (email)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    employment_type VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    technologies VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL,

    CONSTRAINT jobs_pkey
        PRIMARY KEY (id),

    CONSTRAINT jobs_employment_type_check
        CHECK (
            employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'INTERNSHIP',
                'CONTRACT'
            )
        ),

    CONSTRAINT fkkvqdntcagcst2hudgj1u8x443
        FOREIGN KEY (company_id)
        REFERENCES company (id)
);

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    createdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    job_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT job_applications_pkey
        PRIMARY KEY (id),

    CONSTRAINT job_applications_status_check
        CHECK (
            status IN (
                'APPLIED',
                'UNDER_REVIEW',
                'ACCEPTED',
                'REJECTED'
            )
        ),

    CONSTRAINT fkqs2guhg7p83917vto86imuthy
        FOREIGN KEY (user_id)
        REFERENCES users (id),

    CONSTRAINT fkqt4m3c9yiioi16kwsyjrl0cpl
        FOREIGN KEY (job_id)
        REFERENCES jobs (id),

    CONSTRAINT uk_job_application_user_job
        UNIQUE (user_id, job_id)
);